const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES';
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
const FETCH_MORE_MOVIES = 'FETCH_MORE_MOVIES';
const SET_FROM_LOCALSTORAGE = 'GET_FROM_LOCALSTORAGE';
const CHANGE_FILTER = 'CHANGE_FILTER';

export {
  REMOVE_FROM_WATCHLIST,
  ADD_TO_WATCHLIST,
  FETCH_MOVIES_REQUEST,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_FAILURE,
  FETCH_MORE_MOVIES,
  SET_FROM_LOCALSTORAGE,
  CHANGE_FILTER,
};
